#将自定义的头文件添加到编译环境中
DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
#定义项目名称
CONTIKI_PROJECT = blink
#编译所有相关的项目
all: $(CONTIKI_PROJECT)
#定义项目的根目录
CONTIKI = ../../..
#添加编译规则文件
include $(CONTIKI)/Makefile.include
